### ISSUE TITLE
Izložena lozinka

### ISSUE THREAD

**Issue by shtef21** [marinjurisich/TimeKeeper#11]
https://github.com/marinjurisich/TimeKeeper/blob/b93b92fa1e982224223d8139372d3433f340db3e/TimeKeeper/Models/User.cs#L9

Nije li loša praksa držati lozinku unutar klase?

Što misliš o tome da lozinku ni u kojem trenutku ne držimo u RAMu?
Jedino mjesto u kojoj bi lozinka trebala postojati u RAMu servera je funkcija za stvaranje korisnika, koja bi generirala lozinku, heširala je i spremala u bazu.

Prijava korisnika može se izvršiti SQLom bez dohvaćanja lozinke. Na primjer:
```sql
SELECT '...' FROM USERS WHERE USERS.USERNAME = '...' AND USERS.PW_HASH = '...'
```
Ako se vrati 0 redova, tada je neispravna prijava.
Eventualno se može prvo izvršiti zaseban upit za `USERNAME` i vratiti informacija je li barem on ispravan.

**Comment by marinjurisich** [comment]
Nisam razmišljao o tome ali slazem se, lozinku bi trebalo pozivati samo kad ae generira i sprema u bazu

**Comment by shtef21** [comment]
Uglavnom, makneš password pa naknadno možemo dodati.
